<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLyBaiViet" Class="DataTableDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-Q6N4J46\SQLEXPRESS;Initial Catalog=QuanLyBaiViet;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QuanLyBaiVietConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.post" Member="posts">
    <Type Name="post">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="content" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="script" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="category" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="imgName" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="imgFile" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DateCreate" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="isDelete" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="DeleteTime" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>